"""Simulation-calibrated null model for BADASP switch calling.

Background
----------
Each (parent node, child branch, alignment position) gets a score

    score(child) = RC(child) - AC * p_AC(child)

The previous switch-calling rule took the 99.9th percentile of the *observed*
scores within each (event_type x clade-size decile) bin. That is circular: it
manufactures exactly 0.1% "positives" per bin by construction and gives no
error-rate guarantee at all.

This module instead calibrates the threshold against a null generated by
simulating sequence evolution on the *same, fixed* tree under the fitted
substitution model, then re-running the identical ASR + scoring pipeline on
each simulated replicate. Because every replicate is scored with the exact
same tree topology and node names, the null reproduces the identical
(node_name, position) test keys as the observed data, and — crucially — it
reproduces the *dependence structure* between tests (nested clades sharing
leaves, sister branches sharing AC and posteriors, adjacent nodes sharing
subtrees). We never assume independence between tests anywhere in this
module; every guarantee below is either a resampling-based statement that is
valid under arbitrary dependence, or is explicitly flagged as a secondary,
descriptive approximation.

Design decisions carried over from the calling code (not re-litigated here):

* The threshold is GLOBAL across event types (Duplication/Speciation/
  Transfer). The simulator never sees event labels, so conditional on tree
  geometry the null score distribution does not depend on the label; making
  the null event-specific would force equal exceedance rates across D/S/T by
  construction and destroy the event-enrichment signal the study wants to
  measure. `event_type` is used only for reporting, never inside the null.
* The reporting unit is the branch (one score per child per node per
  position). The error-control unit is the node-split: a split is
  "discovered" if EITHER of its two branch scores exceeds the threshold.
  The identical either-branch-exceeds rule is applied when counting null
  exceedances, so that observed and null counts are computed by the same
  procedure.

NaN policy (applies uniformly everywhere in this module)
---------------------------------------------------------
Gap positions in a given branch/replicate produce NaN scores. We adopt one
policy and apply it identically to observed and null data:

* A test's exceedance indicator, ``(left >= t) | (right >= t)``, treats NaN
  branch scores as "does not exceed" — this falls out for free in numpy
  because ``NaN >= t`` is always ``False``. A split with one NaN branch and
  one real branch is therefore still tested on its real branch.
* A split with BOTH branches NaN can never exceed any threshold, in either
  observed or null data, and is therefore silently excluded from every count
  (O(t), V_r(t), exceedance rates) without special-casing — it simply never
  contributes.
* Candidate threshold grids and p-value/quantile computations explicitly
  drop NaN entries before sorting so that NaN does not pollute rank
  statistics (numpy sorts NaN as "largest", which would otherwise corrupt
  counts if not accounted for).

A note on `max(left, right)`
-----------------------------
Internally, several routines compute ``np.fmax(left, right)`` as a single
per-split number. This is used *purely as a monotone computational device*
so that a sort + ``searchsorted``/``cumsum`` can answer "how many splits
have either branch >= t" for every t in one pass. It is mathematically
identical to ``(left >= t) | (right >= t)`` for every threshold t (and
``np.fmax`` inherits the NaN policy above: ``fmax(NaN, x) == x``). It is
never used, reported, or interpreted as a biological "combined score" —
the two branches are the real per-test quantities of interest, and nothing
downstream ever looks at left/right through the lens of "which one was
bigger".
"""

from __future__ import annotations

import warnings
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
from scipy.stats import beta

# Arrays required in every rep_*.npz null-replicate file. See
# `write_null_replicate` / `load_null_scores` docstrings for the exact format.
_NULL_REPLICATE_SCORE_FIELDS = (
    "score_left",
    "score_right",
    "rc_left",
    "rc_right",
    "ac",
    "p_ac_left",
    "p_ac_right",
)
_NULL_REPLICATE_KEY_FIELDS = ("node_name", "position")
_NULL_REPLICATE_OPTIONAL_KEY_FIELDS = ("left_child", "right_child")


# ---------------------------------------------------------------------------
# Null-replicate file I/O
# ---------------------------------------------------------------------------


def write_null_replicate(
    path: Path,
    node_name: Sequence[str],
    position: Sequence[int],
    score_left: Sequence[float],
    score_right: Sequence[float],
    rc_left: Sequence[float],
    rc_right: Sequence[float],
    ac: Sequence[float],
    p_ac_left: Sequence[float],
    p_ac_right: Sequence[float],
    left_child: Optional[Sequence[str]] = None,
    right_child: Optional[Sequence[str]] = None,
) -> None:
    """Write one simulated-replicate file in the ``rep_*.npz`` format.

    File format (this is the canonical definition consumed by
    `load_null_scores`): a ``.npz`` archive containing, on a single shared
    "test" axis of length ``n_tests`` (one entry per (node_name, position)
    scored in that replicate):

    * ``node_name`` (str array) and ``position`` (int array) — the test key.
      Optionally ``left_child`` / ``right_child`` (str arrays) for
      provenance/debugging.
    * ``score_left``, ``score_right``, ``rc_left``, ``rc_right``, ``ac``,
      ``p_ac_left``, ``p_ac_right`` — all float16 arrays of length
      ``n_tests``, matching the columns of ``raw_node_scores.csv``.

    Every replicate written for a given tree/analysis must share the exact
    same key order (same ``node_name``/``position`` at the same array index)
    as every other replicate and as the observed data, since the whole point
    of simulating on the fixed tree is that null and observed tests line up
    one-to-one. `load_null_scores` validates this and fails loudly if it does
    not hold.
    """
    n = len(node_name)
    arrays: Dict[str, np.ndarray] = {
        "node_name": np.asarray(node_name, dtype=str),
        "position": np.asarray(position, dtype=np.int32),
        "score_left": np.asarray(score_left, dtype=np.float16),
        "score_right": np.asarray(score_right, dtype=np.float16),
        "rc_left": np.asarray(rc_left, dtype=np.float16),
        "rc_right": np.asarray(rc_right, dtype=np.float16),
        "ac": np.asarray(ac, dtype=np.float16),
        "p_ac_left": np.asarray(p_ac_left, dtype=np.float16),
        "p_ac_right": np.asarray(p_ac_right, dtype=np.float16),
    }
    for name, arr in arrays.items():
        if arr.shape[0] != n:
            raise ValueError(f"Array '{name}' has length {arr.shape[0]}, expected {n} (from node_name).")
    if left_child is not None:
        arrays["left_child"] = np.asarray(left_child, dtype=str)
    if right_child is not None:
        arrays["right_child"] = np.asarray(right_child, dtype=str)

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    np.savez(path, **arrays)


def load_null_scores(directory: Path) -> Tuple[np.ndarray, np.ndarray, pd.DataFrame]:
    """Load every ``rep_*.npz`` file in `directory` into stacked null arrays.

    Returns
    -------
    null_left, null_right : np.ndarray, shape (R, n_tests), float32
        Per-replicate branch scores, stacked in file-sort order (R = number
        of replicate files found).
    keys : pd.DataFrame, shape (n_tests, ...)
        The shared test key table (``node_name``, ``position``, and
        ``left_child``/``right_child`` if present), taken from the first
        replicate file.

    All replicates must have identical length and identical key order (see
    `write_null_replicate`); a mismatch raises `ValueError` immediately
    rather than silently truncating or reindexing, since silently
    misaligning null and observed tests would invalidate every downstream
    guarantee in this module.
    """
    directory = Path(directory)
    files = sorted(directory.glob("rep_*.npz"))
    if not files:
        raise FileNotFoundError(f"No 'rep_*.npz' files found in {directory}")

    null_left_chunks: List[np.ndarray] = []
    null_right_chunks: List[np.ndarray] = []
    ref_keys: Optional[pd.DataFrame] = None
    ref_n: Optional[int] = None

    required = set(_NULL_REPLICATE_SCORE_FIELDS) | set(_NULL_REPLICATE_KEY_FIELDS)

    for f in files:
        with np.load(f) as data:
            missing = required - set(data.files)
            if missing:
                raise ValueError(f"Replicate file {f} is missing required arrays: {sorted(missing)}")

            n = data["score_left"].shape[0]
            if ref_n is None:
                ref_n = n
                key_cols = {k: data[k] for k in _NULL_REPLICATE_KEY_FIELDS}
                for k in _NULL_REPLICATE_OPTIONAL_KEY_FIELDS:
                    if k in data.files:
                        key_cols[k] = data[k]
                ref_keys = pd.DataFrame(key_cols)
            elif n != ref_n:
                raise ValueError(
                    f"Replicate {f} has {n} tests but reference replicate {files[0]} has {ref_n}. "
                    "All null replicates must score the identical fixed set of (node, position) tests."
                )
            else:
                if not np.array_equal(data["node_name"], ref_keys["node_name"].to_numpy()) or not np.array_equal(
                    data["position"], ref_keys["position"].to_numpy()
                ):
                    raise ValueError(
                        f"Replicate {f} has a different (node_name, position) key order than reference "
                        f"replicate {files[0]}. Null replicates must be written in a shared, fixed key order."
                    )

            null_left_chunks.append(data["score_left"].astype(np.float32))
            null_right_chunks.append(data["score_right"].astype(np.float32))

    null_left = np.stack(null_left_chunks, axis=0)
    null_right = np.stack(null_right_chunks, axis=0)
    assert ref_keys is not None
    return null_left, null_right, ref_keys


def load_observed_scores(csv_path: Path) -> Tuple[np.ndarray, np.ndarray, pd.DataFrame]:
    """Convenience loader for ``raw_node_scores.csv``.

    Returns ``(obs_left, obs_right, keys)`` where `keys` retains the
    reporting columns (``node_name``, ``event_type``, ``position``,
    ``clade_size_left``, ``clade_size_right``, ``distance_from_root``, ...)
    so callers can join threshold decisions back onto them for reporting.
    """
    df = pd.read_csv(csv_path)
    obs_left = df["badasp_score_left"].to_numpy(dtype=np.float32)
    obs_right = df["badasp_score_right"].to_numpy(dtype=np.float32)
    keys = df.drop(columns=["badasp_score_left", "badasp_score_right"])
    return obs_left, obs_right, keys


# ---------------------------------------------------------------------------
# Core statistic: the either-branch-exceeds rule
# ---------------------------------------------------------------------------


def _split_statistic(left: np.ndarray, right: np.ndarray) -> np.ndarray:
    """Monotone stand-in for the either-branch-exceeds rule.

    ``fmax(left, right) >= t`` is exactly ``(left >= t) | (right >= t)`` for
    every threshold t, including the NaN case (`np.fmax` ignores a single NaN
    operand; a split with both branches NaN yields NaN, and ``NaN >= t`` is
    always False). This lets a single sort answer "how many splits exceed t"
    for every t via `searchsorted`, instead of recomputing the OR at every
    grid point. It is a computational device only, not a reported score.
    """
    return np.fmax(np.asarray(left, dtype=np.float64), np.asarray(right, dtype=np.float64))


# ---------------------------------------------------------------------------
# FDP-exceedance calibrated threshold
# ---------------------------------------------------------------------------


@dataclass
class ThresholdResult:
    """Result of `threshold_at_fdr`.

    ``t`` is None when no candidate threshold in the sweep satisfies the
    criterion (see `threshold_at_fdr` docstring for when this happens).
    ``zero_discoveries`` flags the degenerate-but-valid case where the
    chosen threshold admits O(t) == 0 observed discoveries.
    """

    t: Optional[float]
    O_t: Optional[int]
    E_fp: Optional[float]
    E_fp_over_O: Optional[float]
    fdp_quantile_achieved: Optional[float]
    q: float
    fdp_quantile: float
    R: int
    criterion_met: bool
    zero_discoveries: bool
    sweep: pd.DataFrame
    note: str = ""


def threshold_at_fdr(
    obs_left: np.ndarray,
    obs_right: np.ndarray,
    null_left: np.ndarray,
    null_right: np.ndarray,
    q: float,
    fdp_quantile: float = 0.90,
) -> ThresholdResult:
    """Pick the smallest split-level threshold controlling P(FDP > q).

    For a candidate threshold t:

    * ``O(t)`` = number of observed node-splits with either branch score
      ``>= t`` (NaN-both splits never count, see module docstring).
    * ``V_r(t)`` = the identical either-branch-exceeds count computed on
      null replicate r.
    * ``E[FP](t) = mean_r V_r(t)`` is the point estimate of the expected
      number of false discoveries at t; ``E[FP](t) / O(t)`` estimates the
      false discovery proportion.

    Primary criterion: choose the smallest t (searched over the sorted
    unique *observed* split statistics — O(t) only changes at these
    breakpoints, so it is exactly as informative as a finer grid while being
    only O(n_tests) points) such that the `fdp_quantile` percentile
    (default: 90th) of ``V_r(t) / max(O(t), 1)`` over replicates is ``<= q``.
    This controls ``P(FDP(t) > q) <= 1 - fdp_quantile`` and remains valid
    under arbitrary dependence between tests, because the null replicates
    were generated by simulating on the identical tree and therefore
    reproduce the real dependence structure (shared clades, shared AC/
    posteriors at a node, shared subtrees) rather than assuming independence.

    This is a resampling/Monte-Carlo quantile, not an asymptotic
    approximation: it is only as good as the number of replicates R:
    the achievable resolution/granularity of the estimated tail quantile is
    limited by R, and `E[FP]` and the FDP quantile are themselves noisy
    point estimates from R draws.

    Complexity
    ----------
    Let ``n`` = number of observed node-splits and ``m <= n`` = number of
    grid points (unique finite observed split statistics). Null replicates
    are sorted once with a single vectorized ``np.sort(null_stat, axis=1)``
    call, O(R * n log n). Counting exceedances at every grid point uses
    `searchsorted` against each replicate's sorted (NaN-stripped) row,
    O(R * m log n). Total: O(R * n log n) — no O(m * R * n) double loop.

    Degenerate cases
    ----------------
    * If every observed split statistic is NaN, there is no candidate grid;
      returns a `ThresholdResult` with ``t=None``, ``criterion_met=False``,
      and an explanatory `note`.
    * If no t in the grid satisfies the criterion, returns ``t=None``,
      ``criterion_met=False``, with the full sweep still attached so the
      caller can inspect how close the best candidate came.
    * The chosen t may have ``O(t) == 0`` (no observed discoveries survive)
      — this is a valid, non-error outcome, flagged via
      ``zero_discoveries=True``.
    """
    obs_left = np.asarray(obs_left, dtype=np.float64)
    obs_right = np.asarray(obs_right, dtype=np.float64)
    null_left = np.asarray(null_left, dtype=np.float64)
    null_right = np.asarray(null_right, dtype=np.float64)

    n = obs_left.shape[0]
    if obs_right.shape[0] != n:
        raise ValueError("obs_left and obs_right must have the same length.")
    if null_left.shape != null_right.shape:
        raise ValueError("null_left and null_right must have identical shape.")
    if null_left.shape[1] != n:
        raise ValueError(f"null arrays have {null_left.shape[1]} tests but observed arrays have {n}.")

    R = null_left.shape[0]
    obs_stat = _split_statistic(obs_left, obs_right)
    finite_obs = obs_stat[np.isfinite(obs_stat)]

    empty_sweep = pd.DataFrame(
        columns=["t", "O", "E_fp", "E_fp_over_O", "fdp_quantile_achieved", "meets_criterion"]
    )

    if finite_obs.size == 0:
        return ThresholdResult(
            t=None,
            O_t=None,
            E_fp=None,
            E_fp_over_O=None,
            fdp_quantile_achieved=None,
            q=q,
            fdp_quantile=fdp_quantile,
            R=R,
            criterion_met=False,
            zero_discoveries=False,
            sweep=empty_sweep,
            note="All observed split statistics are NaN; no candidate thresholds exist.",
        )

    t_grid = np.unique(finite_obs)  # ascending
    m = t_grid.shape[0]
    sorted_valid_obs = np.sort(finite_obs)
    idx_obs = np.searchsorted(sorted_valid_obs, t_grid, side="left")
    O_grid = (finite_obs.size - idx_obs).astype(np.int64)  # shape (m,)

    if R == 0:
        return ThresholdResult(
            t=None,
            O_t=None,
            E_fp=None,
            E_fp_over_O=None,
            fdp_quantile_achieved=None,
            q=q,
            fdp_quantile=fdp_quantile,
            R=0,
            criterion_met=False,
            zero_discoveries=False,
            sweep=empty_sweep,
            note="No null replicates (R=0); cannot calibrate a threshold.",
        )

    null_stat = _split_statistic(null_left, null_right)  # (R, n)
    sorted_null = np.sort(null_stat, axis=1)  # NaNs sort to the end of each row; vectorized once, O(R n log n)
    valid_counts = np.sum(~np.isnan(null_stat), axis=1)  # (R,)

    V_grid = np.empty((R, m), dtype=np.int64)
    for r in range(R):
        vc = int(valid_counts[r])
        row_valid = sorted_null[r, :vc]
        idx = np.searchsorted(row_valid, t_grid, side="left")
        V_grid[r] = vc - idx

    E_fp = V_grid.mean(axis=0)
    O_safe = np.maximum(O_grid, 1)
    E_fp_over_O = E_fp / O_safe
    fdp = V_grid / O_safe[np.newaxis, :]
    achieved = np.quantile(fdp, fdp_quantile, axis=0)
    meets = achieved <= q

    sweep = pd.DataFrame(
        {
            "t": t_grid,
            "O": O_grid,
            "E_fp": E_fp,
            "E_fp_over_O": E_fp_over_O,
            "fdp_quantile_achieved": achieved,
            "meets_criterion": meets,
        }
    )

    if not meets.any():
        return ThresholdResult(
            t=None,
            O_t=None,
            E_fp=None,
            E_fp_over_O=None,
            fdp_quantile_achieved=None,
            q=q,
            fdp_quantile=fdp_quantile,
            R=R,
            criterion_met=False,
            zero_discoveries=False,
            sweep=sweep,
            note=f"No threshold in the grid achieves P(FDP > {q}) <= {1 - fdp_quantile:.3g}.",
        )

    chosen_idx = int(np.argmax(meets))  # first True, i.e. smallest t satisfying the criterion
    row = sweep.iloc[chosen_idx]
    return ThresholdResult(
        t=float(row["t"]),
        O_t=int(row["O"]),
        E_fp=float(row["E_fp"]),
        E_fp_over_O=float(row["E_fp_over_O"]),
        fdp_quantile_achieved=float(row["fdp_quantile_achieved"]),
        q=q,
        fdp_quantile=fdp_quantile,
        R=R,
        criterion_met=True,
        zero_discoveries=bool(row["O"] == 0),
        sweep=sweep,
        note="",
    )


# ---------------------------------------------------------------------------
# Threshold description: report an error rate for an externally chosen t
# ---------------------------------------------------------------------------
#
# `threshold_at_fdr` above SELECTS a threshold: it sweeps a grid and returns
# `t=None` whenever no candidate meets the criterion, which silently drops
# the case entirely. The functions below never select anything. They take a
# threshold `t` that the caller already picked by some external rule (e.g. a
# fixed number of calls the downstream analysis wants to make) and describe
# what that specific choice costs against the same simulation-based null,
# so a number is always reported even when it is an unflattering one.


def _jsonable(obj: object) -> object:
    """Recursively convert numpy containers to plain Python for `json.dumps`.

    Arrays become lists, numpy scalars (including `np.bool_`) become the
    corresponding Python `float`/`int`/`bool`, and dict keys that are numpy
    scalars are converted the same way. Everything else passes through
    unchanged.
    """
    if isinstance(obj, np.ndarray):
        return [_jsonable(v) for v in obj.tolist()]
    if isinstance(obj, np.generic):
        return obj.item()
    if isinstance(obj, dict):
        return {(k.item() if isinstance(k, np.generic) else k): _jsonable(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [_jsonable(v) for v in obj]
    return obj


@dataclass
class ThresholdDescription:
    """Error-rate description of a single, externally chosen threshold `t`.

    Unlike `ThresholdResult`, `t` here is never `None` and is never selected
    by this module — it is an input, describing whatever threshold the
    caller's own rule (e.g. "call the top N") already settled on. Every
    field is a *description* of that choice against the simulation-based
    null, not a pass/fail verdict.

    Fields
    ------
    t, O, R : the threshold itself, the observed exceedance count at it, and
        the number of null replicates it was evaluated against.
    V : shape (R,) int64, the per-replicate null exceedance count `V_r(t)`.
    E_fp, E_fp_over_O, O_over_E_fp : mean of `V` and the two ways of ratioing
        it against `O` (see `describe_threshold` for why both directions are
        reported). `O_over_E_fp` is `None` when `E_fp == 0` (undefined ratio).
    fdp_mean, fdp_median, fdp_min, fdp_max : summary of `V / max(O, 1)` across
        replicates.
    fdp_quantile, fdp_quantile_achieved : the requested quantile level
        (echoed back) and the value of `V / max(O, 1)` actually achieved at
        that level.
    mc_pvalue, n_ge_observed : the Monte-Carlo p-value described in
        `describe_threshold` and the raw count behind it.
    labels, label_summary, mixture, group_composition : optional two-state
        replicate bookkeeping, present only when `labels` (and `groups`) were
        supplied to `describe_threshold`.
    notes : free-text caveats attached during computation (e.g. when the
        null produces more calls than were observed).
    bootstrap : optional nonparametric bootstrap interval on the mean and
        `fdp_quantile`-th percentile of `V / max(O, 1)`, present only when
        `n_bootstrap > 0` was passed to `describe_threshold`. This is
        deliberately separate from `mixture`: the two-state mixture interval
        is a *model* of the between-replicate spread that can fail (see its
        falsifiers), while this bootstrap interval assumes nothing about the
        shape of that spread.
    """

    t: float
    O: int
    R: int
    V: np.ndarray
    E_fp: float
    E_fp_over_O: float
    O_over_E_fp: Optional[float]
    fdp_mean: float
    fdp_median: float
    fdp_min: float
    fdp_max: float
    fdp_quantile: float
    fdp_quantile_achieved: float
    mc_pvalue: float
    n_ge_observed: int
    labels: Optional[np.ndarray]
    label_summary: Optional[dict]
    mixture: Optional[dict]
    group_composition: Optional[dict]
    notes: List[str]
    bootstrap: Optional[dict] = None

    def to_dict(self) -> dict:
        """JSON-serialisable dict (numpy arrays -> lists, numpy scalars -> Python)."""
        return {
            "t": float(self.t),
            "O": int(self.O),
            "R": int(self.R),
            "V": _jsonable(self.V),
            "E_fp": float(self.E_fp),
            "E_fp_over_O": float(self.E_fp_over_O),
            "O_over_E_fp": None if self.O_over_E_fp is None else float(self.O_over_E_fp),
            "fdp_mean": float(self.fdp_mean),
            "fdp_median": float(self.fdp_median),
            "fdp_min": float(self.fdp_min),
            "fdp_max": float(self.fdp_max),
            "fdp_quantile": float(self.fdp_quantile),
            "fdp_quantile_achieved": float(self.fdp_quantile_achieved),
            "mc_pvalue": float(self.mc_pvalue),
            "n_ge_observed": int(self.n_ge_observed),
            "labels": None if self.labels is None else _jsonable(self.labels),
            "label_summary": None if self.label_summary is None else _jsonable(self.label_summary),
            "mixture": None if self.mixture is None else _jsonable(self.mixture),
            "group_composition": None if self.group_composition is None else _jsonable(self.group_composition),
            "notes": list(self.notes),
            "bootstrap": None if self.bootstrap is None else _jsonable(self.bootstrap),
        }


def describe_threshold(
    t: float,
    obs_left: np.ndarray,
    obs_right: np.ndarray,
    null_left: np.ndarray,
    null_right: np.ndarray,
    *,
    labels: Optional[np.ndarray] = None,
    label_statistic: Optional[np.ndarray] = None,
    groups: Optional[np.ndarray] = None,
    fdp_quantile: float = 0.90,
    ci_level: float = 0.95,
    gap_ratio_threshold: float = 2.0,
    n_bootstrap: int = 0,
    bootstrap_seed: Optional[int] = None,
    bootstrap_unit: str = "replicate",
) -> ThresholdDescription:
    """Describe the error rate of a threshold `t` chosen outside this module.

    This function never searches a grid and never returns `t=None`: `t` is
    a required, fixed input, validated only for being finite. Its purpose is
    the complement of `threshold_at_fdr` — instead of picking the smallest
    threshold that clears a bar, it reports what a threshold someone already
    committed to (e.g. "call the top N splits") actually costs against the
    null.

    Exceedance counting reuses the module's either-branch-exceeds rule via
    `_split_statistic`: `O` is the number of observed splits with
    `_split_statistic(obs_left, obs_right) >= t`, and `V[r]` is the identical
    count for null replicate r, both ignoring NaN (a split with both
    branches NaN never counts, same policy as `threshold_at_fdr`). Both
    counts are obtained by sorting once and using `searchsorted` rather than
    a per-element Python comparison loop, mirroring `threshold_at_fdr`'s
    approach.

    Monte-Carlo p-value
    --------------------
    ``mc_pvalue = (1 + #{r : V_r >= O}) / (1 + R)`` tests whether the
    observed number of calls at this threshold is distinguishable from the
    number of calls this same null produces on its own, i.e. whether `O` is
    an outlier relative to the `V_r` distribution. Like `per_test_pvalues`,
    the +1 in numerator and denominator means the smallest attainable value
    is `1 / (1 + R)` — with R replicates you cannot report a smaller
    Monte-Carlo p-value than that, no matter how extreme `O` is.

    E_fp_over_O vs. O_over_E_fp
    ----------------------------
    `E_fp_over_O = mean(V) / max(O, 1)` is the usual false-discovery-style
    ratio. `O_over_E_fp` is its reciprocal (`None` when `E_fp == 0`, since
    the ratio is undefined). Both are reported, unclipped, because
    `E_fp_over_O` can legitimately exceed 1: that happens when the null
    alone produces more calls than the observed data contains, at which
    point the quantity is no longer interpretable as a false-discovery
    proportion (a proportion cannot exceed 1) but rather as evidence that
    the null overshoots the observed data at this threshold. When that
    happens a note is appended to `notes` rather than the value being
    truncated to 1.

    Two-state replicate labels (optional)
    ---------------------------------------
    Background: the between-replicate spread of `V_r` at a fixed threshold
    has been observed to look like a two-state mixture (most replicates
    cluster tightly, a minority sit several times higher) rather than a
    smooth, normal-theory spread. If the caller supplies a boolean `labels`
    array (length R, True = "high-state" replicate) reflecting that split,
    this function reports:

    * `label_summary`: per-group mean/sd of `V` (`sd` uses ddof=1, `None`
      when a group has fewer than 2 members).
    * `mixture`: `pi_hat = n_high / R`, a Clopper-Pearson exact binomial
      interval on that proportion at `ci_level` (via
      `scipy.stats.beta.ppf`), and the implied `fdp` at `pi_hat` and at each
      interval endpoint, computed as
      ``((1 - pi) * mean_V_low + pi * mean_V_high) / max(O, 1)``. The
      interval is built from the *proportion of high-state replicates*
      rather than a normal-theory standard error on `V_r` directly, because
      the two-state pattern means the ordinary CLT-based SE is the wrong
      description of the uncertainty here.
    * `mixture["falsifiers"]`: sanity checks on the label itself, not on the
      mixture math — each is at least a `{"value": bool, "explanation": str}`
      pair describing what a `True` value would mean:
        - `"low_state_exceeds_high_minimum"`: a low-labelled replicate has
          `V` at or above the minimum `V` among high-labelled replicates.
        - `"n_high_below_2"`: fewer than 2 replicates are labelled
          high-state, so the binomial interval is essentially uninformative.
        - `"gap_not_dominant"`: computed on `label_statistic` (the
          per-replicate scalar the labels were cut from), not on `V`. Sort
          `label_statistic`, take consecutive differences, and compute
          `gap_ratio = largest_gap / second_largest_gap`. A genuinely
          bimodal `label_statistic` shows one dominant gap separating the
          two states; a continuous, right-skewed sample instead shows
          several comparable gaps. `True` when
          `gap_ratio < gap_ratio_threshold`, i.e. the largest gap is not
          clearly dominant, which is evidence against a real two-state
          structure in `label_statistic` (independent of where the cut was
          placed). The dict also carries `gap_ratio`, `largest_gap`,
          `second_largest_gap`, and `largest_gap_between` (the two
          `label_statistic` values the largest gap sits between).
        - `"cut_not_at_largest_gap"`: also computed on `label_statistic`.
          The label cut is reconstructed empirically as the interval between
          `max(label_statistic[~labels])` and `min(label_statistic[labels])`;
          `True` when that interval's endpoints do not coincide with the
          largest gap's endpoints, i.e. the cut used to build `labels` was
          not placed at the most prominent break in `label_statistic`. The
          dict also carries `cut_between` and `cut_gap_width`.
        - `"gap_not_dominant"` and `"cut_not_at_largest_gap"` are both
          `{"value": None, "skipped": str}` instead of the usual shape when
          `label_statistic` is not supplied, since neither can be computed
          from `V` alone.
      None of these being True is not proof the label is correct; any of
      them being True is evidence the two-state label does not hold here.

    If `groups` (length R, one invocation id per replicate) is supplied
    together with `labels`, `group_composition` reports, per group, how many
    replicates came from it and how many of those are high-state — purely
    descriptive counts, no ICC or test statistic is computed here.

    Nonparametric bootstrap interval (optional, off by default)
    -------------------------------------------------------------
    The `mixture` interval above is a two-state *model* of the spread of
    `V_r`, and it self-reports via `mixture["falsifiers"]` when that model
    does not hold on a given dataset. When `n_bootstrap > 0`, a second,
    model-free interval is computed instead by resampling the R
    per-replicate `V` values with replacement `n_bootstrap` times and taking
    the `ci_level` percentile interval of the resampled mean and of the
    resampled `fdp_quantile`-th percentile (both expressed as `fdp`, i.e.
    divided by `max(O, 1)`). This assumes nothing about the shape of the
    between-replicate distribution, at the cost of not being usable to
    describe a labelled two-state split the way `mixture` is.

    `bootstrap_seed` is required (not `None`) whenever `n_bootstrap > 0`, so
    that a reported interval is always reproducible from the stored seed
    rather than depending on unlogged global RNG state.

    `bootstrap_unit` controls the resampling unit:

    * `"replicate"` (default): resample individual replicates' `V` values.
    * `"group"`: requires `groups`; resample whole groups (as named by
      `groups`) with replacement and concatenate the `V` values of the drawn
      groups, so the resampled sample size varies naturally with how many
      replicates the drawn groups happen to contain. Use this to check
      whether within-group correlation (e.g. multiple replicates from the
      same simulate invocation) makes the replicate-level interval too
      narrow — this is an open empirical question, not assumed either way.

    The result is stored in the `bootstrap` field as a dict with keys
    `n_bootstrap`, `seed`, `ci_level`, `resample_unit`, `mean_fdp_ci_low`,
    `mean_fdp_ci_high`, `fdp_quantile_ci_low`, `fdp_quantile_ci_high`.
    `bootstrap` is `None` when `n_bootstrap == 0` (the default), leaving
    every other field exactly as it was before this option existed.

    Parameters
    ----------
    t : float
        The threshold to describe. Must be finite.
    obs_left, obs_right : np.ndarray, shape (n,)
        Observed branch scores.
    null_left, null_right : np.ndarray, shape (R, n)
        Null branch scores.
    labels : Optional[np.ndarray], shape (R,), bool
        True marks a "high-state" null replicate.
    label_statistic : Optional[np.ndarray], shape (R,)
        The per-replicate scalar `labels` was derived from by cutting it at
        some threshold (e.g. per-replicate P(AC=-1)). Used only to compute
        the `"gap_not_dominant"` and `"cut_not_at_largest_gap"` falsifiers in
        `mixture["falsifiers"]`, which test whether `label_statistic` itself
        looks bimodal and whether the cut lands on its largest gap — as
        opposed to testing separation on `V`, which conflates the label's
        validity with whether the cut happens to also split `V` (V can be
        strongly correlated with `label_statistic` even when the labelling
        cut itself is arbitrary). Ignored when `labels` is None. When
        `labels` is given without `label_statistic`, both falsifiers are
        reported as skipped rather than silently omitted.
    groups : Optional[np.ndarray], shape (R,)
        Which simulate invocation each replicate came from.
    fdp_quantile : float
        Quantile level of `V / max(O, 1)` to report as `fdp_quantile_achieved`
        (and, when bootstrapping, as `fdp_quantile_ci_low`/`_ci_high`).
    ci_level : float
        Confidence level for the Clopper-Pearson interval on `pi_hat`, and
        (when `n_bootstrap > 0`) for the bootstrap percentile interval.
    gap_ratio_threshold : float
        Threshold on `gap_ratio` (largest gap / second-largest gap in sorted
        `label_statistic`) below which `"gap_not_dominant"` fires. Default
        2.0, i.e. the largest gap must be at least twice the second-largest
        gap for the sample to be called dominantly bimodal.
    n_bootstrap : int
        Number of bootstrap resamples. `0` (default) skips the bootstrap
        entirely.
    bootstrap_seed : Optional[int]
        Seed for `np.random.default_rng`. Required whenever `n_bootstrap > 0`.
    bootstrap_unit : str
        `"replicate"` (default) or `"group"`. See above.

    Returns
    -------
    ThresholdDescription
    """
    if not np.isfinite(t):
        raise ValueError(
            "t must be finite: describe_threshold does not select a threshold, "
            "it only describes one already chosen by the caller."
        )

    obs_left = np.asarray(obs_left, dtype=np.float64)
    obs_right = np.asarray(obs_right, dtype=np.float64)
    null_left = np.asarray(null_left, dtype=np.float64)
    null_right = np.asarray(null_right, dtype=np.float64)

    n = obs_left.shape[0]
    if obs_right.shape[0] != n:
        raise ValueError("obs_left and obs_right must have the same length.")
    if null_left.shape != null_right.shape:
        raise ValueError("null_left and null_right must have identical shape.")
    if null_left.shape[1] != n:
        raise ValueError(f"null arrays have {null_left.shape[1]} tests but observed arrays have {n}.")

    R = null_left.shape[0]
    t = float(t)

    obs_stat = _split_statistic(obs_left, obs_right)
    finite_obs = obs_stat[np.isfinite(obs_stat)]
    sorted_valid_obs = np.sort(finite_obs)
    O = int(finite_obs.size - np.searchsorted(sorted_valid_obs, t, side="left"))

    null_stat = _split_statistic(null_left, null_right)  # (R, n)
    sorted_null = np.sort(null_stat, axis=1)  # NaNs sort to the end of each row
    valid_counts = np.sum(~np.isnan(null_stat), axis=1)  # (R,)
    V = np.empty(R, dtype=np.int64)
    for r in range(R):
        vc = int(valid_counts[r])
        row_valid = sorted_null[r, :vc]
        idx = np.searchsorted(row_valid, t, side="left")
        V[r] = vc - idx

    notes: List[str] = []
    E_fp = float(V.mean()) if R > 0 else float("nan")
    O_safe = max(O, 1)
    E_fp_over_O = E_fp / O_safe
    O_over_E_fp = None if E_fp == 0 else O_safe / E_fp
    if E_fp_over_O > 1:
        notes.append(
            f"E_fp_over_O = {E_fp_over_O:.4g} > 1: at this threshold the null produces "
            "more calls than the observed data contains, so this ratio is not "
            "interpretable as a false-discovery proportion."
        )

    fdp = V / O_safe
    fdp_mean = float(fdp.mean())
    fdp_median = float(np.median(fdp))
    fdp_min = float(fdp.min())
    fdp_max = float(fdp.max())
    fdp_quantile_achieved = float(np.quantile(fdp, fdp_quantile))

    n_ge_observed = int(np.sum(V >= O))
    mc_pvalue = (1.0 + n_ge_observed) / (1.0 + R)

    labels_arr: Optional[np.ndarray] = None
    label_summary: Optional[dict] = None
    mixture: Optional[dict] = None
    group_composition: Optional[dict] = None

    if labels is not None:
        labels_arr = np.asarray(labels, dtype=bool)
        if labels_arr.shape[0] != R:
            raise ValueError("labels must have length R (one entry per null replicate).")

        n_high = int(labels_arr.sum())
        n_low = int(R - n_high)
        V_high = V[labels_arr]
        V_low = V[~labels_arr]

        mean_V_high = float(V_high.mean()) if n_high > 0 else float("nan")
        sd_V_high = float(V_high.std(ddof=1)) if n_high >= 2 else None
        mean_V_low = float(V_low.mean()) if n_low > 0 else float("nan")
        sd_V_low = float(V_low.std(ddof=1)) if n_low >= 2 else None

        label_summary = {
            "n_high": n_high,
            "n_low": n_low,
            "mean_V_high": mean_V_high,
            "sd_V_high": sd_V_high,
            "mean_V_low": mean_V_low,
            "sd_V_low": sd_V_low,
        }

        alpha = 1.0 - ci_level
        k = n_high
        pi_hat = k / R
        pi_low = 0.0 if k == 0 else float(beta.ppf(alpha / 2.0, k, R - k + 1))
        pi_high = 1.0 if k == R else float(beta.ppf(1.0 - alpha / 2.0, k + 1, R - k))

        def _fdp_at(pi: float) -> float:
            return ((1.0 - pi) * mean_V_low + pi * mean_V_high) / O_safe

        if n_high > 0 and n_low > 0:
            high_min = float(V_high.min())
            low_state_exceeds_high_minimum = bool(np.any(V_low >= high_min))
        else:
            low_state_exceeds_high_minimum = False

        # gap_not_dominant / cut_not_at_largest_gap: checks on the labelling
        # variable's own distribution (label_statistic), not on V. This
        # replaces the old "labels_not_separating" check on V, which was
        # uninformative: V is strongly monotone in label_statistic, so
        # whether V happens to separate tests only the cut, not whether
        # label_statistic is genuinely bimodal.
        if label_statistic is None:
            skip_reason = (
                "label_statistic was not provided to describe_threshold, so this "
                "check on the labelling variable's own distribution could not be "
                "computed."
            )
            gap_not_dominant_entry = {"value": None, "skipped": skip_reason}
            cut_not_at_largest_gap_entry = {"value": None, "skipped": skip_reason}
        else:
            label_statistic_arr = np.asarray(label_statistic, dtype=np.float64)
            if label_statistic_arr.shape[0] != R:
                raise ValueError("label_statistic must have length R (one entry per null replicate).")

            sorted_stat = np.sort(label_statistic_arr)
            diffs = np.diff(sorted_stat)
            if diffs.size == 0:
                # R <= 1: no gaps at all, nothing to compare.
                gap_ratio = float("nan")
                largest_gap = float("nan")
                second_largest_gap = float("nan")
                largest_gap_between = [None, None]
            else:
                order = np.argsort(diffs)[::-1]  # descending
                largest_idx = int(order[0])
                largest_gap = float(diffs[largest_idx])
                largest_gap_between = [float(sorted_stat[largest_idx]), float(sorted_stat[largest_idx + 1])]
                if diffs.size >= 2:
                    second_largest_gap = float(diffs[int(order[1])])
                    gap_ratio = float("inf") if second_largest_gap == 0 else largest_gap / second_largest_gap
                else:
                    # Only one gap exists (R == 2): trivially dominant.
                    second_largest_gap = None
                    gap_ratio = float("inf")

            gap_not_dominant_value = bool(np.isfinite(gap_ratio) and gap_ratio < gap_ratio_threshold)
            gap_not_dominant_entry = {
                "value": gap_not_dominant_value,
                "explanation": (
                    f"If True, the largest gap in sorted label_statistic is not clearly "
                    f"dominant over the second-largest gap (gap_ratio < "
                    f"{gap_ratio_threshold:g}). A genuinely bimodal label_statistic shows "
                    "one dominant gap separating the two states, whereas a continuous, "
                    "right-skewed sample shows several comparable gaps -- so a small "
                    "gap_ratio is evidence against a real two-state structure in "
                    "label_statistic, independent of where the label cut was placed."
                ),
                "gap_ratio": gap_ratio,
                "largest_gap": largest_gap,
                "second_largest_gap": second_largest_gap,
                "largest_gap_between": largest_gap_between,
            }

            if n_high > 0 and n_low > 0:
                cut_low = float(np.max(label_statistic_arr[~labels_arr]))
                cut_high = float(np.min(label_statistic_arr[labels_arr]))
                cut_gap_width = cut_high - cut_low
                cut_between = [cut_low, cut_high]
                cut_matches_largest_gap = (
                    largest_gap_between[0] is not None
                    and np.isclose(cut_low, largest_gap_between[0])
                    and np.isclose(cut_high, largest_gap_between[1])
                )
                cut_not_at_largest_gap_value = bool(not cut_matches_largest_gap)
            else:
                cut_gap_width = None
                cut_between = [None, None]
                cut_not_at_largest_gap_value = False

            cut_not_at_largest_gap_entry = {
                "value": cut_not_at_largest_gap_value,
                "explanation": (
                    "If True, the label cut -- reconstructed empirically as the interval "
                    "between max(label_statistic[~labels]) and min(label_statistic[labels]) "
                    "-- does not coincide with the largest gap in sorted label_statistic, "
                    "meaning the cut used to build labels was not placed at the most "
                    "prominent break in the data."
                ),
                "cut_between": cut_between,
                "cut_gap_width": cut_gap_width,
                "largest_gap_between": largest_gap_between,
            }

        falsifiers = {
            "low_state_exceeds_high_minimum": {
                "value": bool(low_state_exceeds_high_minimum),
                "explanation": (
                    "If True, at least one low-labelled replicate has V at or above "
                    "the minimum V among high-labelled replicates, meaning the "
                    "two-state label does not cleanly separate replicates by V."
                ),
            },
            "n_high_below_2": {
                "value": bool(n_high < 2),
                "explanation": (
                    "If True, fewer than 2 replicates are labelled high-state, so "
                    "the Clopper-Pearson interval on pi_hat is built from too few "
                    "successes to be informative."
                ),
            },
            "gap_not_dominant": gap_not_dominant_entry,
            "cut_not_at_largest_gap": cut_not_at_largest_gap_entry,
        }

        mixture = {
            "pi_hat": pi_hat,
            "pi_low": pi_low,
            "pi_high": pi_high,
            "fdp_at_pi_hat": _fdp_at(pi_hat),
            "fdp_at_pi_low": _fdp_at(pi_low),
            "fdp_at_pi_high": _fdp_at(pi_high),
            "falsifiers": falsifiers,
        }

        if groups is not None:
            groups_arr = np.asarray(groups)
            if groups_arr.shape[0] != R:
                raise ValueError("groups must have length R (one entry per null replicate).")
            group_composition = {}
            for g in np.unique(groups_arr):
                mask = groups_arr == g
                key = g.item() if isinstance(g, np.generic) else g
                group_composition[key] = {
                    "n": int(mask.sum()),
                    "n_high": int(np.sum(labels_arr[mask])),
                }
    elif groups is not None and not (n_bootstrap > 0 and bootstrap_unit == "group"):
        notes.append("groups was provided without labels; group_composition requires both and was not computed.")

    bootstrap: Optional[dict] = None
    if n_bootstrap < 0:
        raise ValueError("n_bootstrap must be >= 0.")
    if n_bootstrap > 0:
        if bootstrap_seed is None:
            raise ValueError(
                "bootstrap_seed must be given (not None) whenever n_bootstrap > 0, "
                "so a reported bootstrap interval is always reproducible."
            )
        if bootstrap_unit not in ("replicate", "group"):
            raise ValueError(f"bootstrap_unit must be 'replicate' or 'group', got {bootstrap_unit!r}.")
        if bootstrap_unit == "group" and groups is None:
            raise ValueError("bootstrap_unit='group' requires groups to be given.")

        boot_rng = np.random.default_rng(bootstrap_seed)
        boot_means = np.empty(n_bootstrap, dtype=np.float64)
        boot_quantiles = np.empty(n_bootstrap, dtype=np.float64)

        if bootstrap_unit == "replicate":
            for b in range(n_bootstrap):
                resample = boot_rng.choice(V, size=R, replace=True)
                boot_means[b] = resample.mean()
                boot_quantiles[b] = np.quantile(resample, fdp_quantile)
            resample_unit = "replicate"
        else:  # "group"
            groups_arr_b = np.asarray(groups)
            if groups_arr_b.shape[0] != R:
                raise ValueError("groups must have length R (one entry per null replicate).")
            unique_groups_b = np.unique(groups_arr_b)
            group_to_V = {g: V[groups_arr_b == g] for g in unique_groups_b}
            for b in range(n_bootstrap):
                drawn = boot_rng.choice(unique_groups_b, size=unique_groups_b.shape[0], replace=True)
                resample = np.concatenate([group_to_V[g] for g in drawn])
                boot_means[b] = resample.mean()
                boot_quantiles[b] = np.quantile(resample, fdp_quantile)
            resample_unit = "group"

        boot_mean_fdp = boot_means / O_safe
        boot_quantile_fdp = boot_quantiles / O_safe
        alpha_b = 1.0 - ci_level
        lo_pct = 100.0 * alpha_b / 2.0
        hi_pct = 100.0 * (1.0 - alpha_b / 2.0)
        bootstrap = {
            "n_bootstrap": int(n_bootstrap),
            "seed": int(bootstrap_seed),
            "ci_level": float(ci_level),
            "resample_unit": resample_unit,
            "mean_fdp_ci_low": float(np.percentile(boot_mean_fdp, lo_pct)),
            "mean_fdp_ci_high": float(np.percentile(boot_mean_fdp, hi_pct)),
            "fdp_quantile_ci_low": float(np.percentile(boot_quantile_fdp, lo_pct)),
            "fdp_quantile_ci_high": float(np.percentile(boot_quantile_fdp, hi_pct)),
        }

    return ThresholdDescription(
        t=t,
        O=O,
        R=R,
        V=V,
        E_fp=E_fp,
        E_fp_over_O=E_fp_over_O,
        O_over_E_fp=O_over_E_fp,
        fdp_mean=fdp_mean,
        fdp_median=fdp_median,
        fdp_min=fdp_min,
        fdp_max=fdp_max,
        fdp_quantile=float(fdp_quantile),
        fdp_quantile_achieved=fdp_quantile_achieved,
        mc_pvalue=mc_pvalue,
        n_ge_observed=n_ge_observed,
        labels=labels_arr,
        label_summary=label_summary,
        mixture=mixture,
        group_composition=group_composition,
        notes=notes,
        bootstrap=bootstrap,
    )


def describe_threshold_curve(
    obs_left: np.ndarray,
    obs_right: np.ndarray,
    null_left: np.ndarray,
    null_right: np.ndarray,
    *,
    call_counts: Iterable[int],
    **kwargs: object,
) -> pd.DataFrame:
    """`describe_threshold` evaluated at a curve of externally chosen call counts.

    For each `target` in `call_counts`, a threshold is derived purely from
    the *observed* split statistic as
    ``t = np.quantile(finite_obs, 1 - target / finite_obs.size)`` and passed
    to `describe_threshold` unchanged (`target` never touches the null).
    Because the observed statistic has ties and atoms, the resulting `O` at
    that `t` is not guaranteed to equal `target` exactly — it is documented
    here as an approximate correspondence, not an exact one.

    All keyword arguments accepted by `describe_threshold`
    (`labels`, `groups`, `fdp_quantile`, `ci_level`) may be passed through
    via `**kwargs` and are applied identically to every row.

    Parameters
    ----------
    obs_left, obs_right : np.ndarray, shape (n,)
    null_left, null_right : np.ndarray, shape (R, n)
    call_counts : Iterable[int]
        Target observed-call counts to evaluate a threshold at.
    **kwargs
        Forwarded to `describe_threshold` (see its docstring).

    Returns
    -------
    pd.DataFrame, one row per target in `call_counts`, sorted ascending by
    `target_calls`, with columns:
    ``target_calls, t, O, E_fp, E_fp_over_O, O_over_E_fp, fdp_median,
    fdp_q<level>, fdp_min, fdp_max, mc_pvalue, n_ge_observed``, plus
    ``pi_hat, fdp_at_pi_hat, fdp_at_pi_low, fdp_at_pi_high`` when `labels`
    is among `kwargs`.
    """
    obs_left = np.asarray(obs_left, dtype=np.float64)
    obs_right = np.asarray(obs_right, dtype=np.float64)
    obs_stat = _split_statistic(obs_left, obs_right)
    finite_obs = obs_stat[np.isfinite(obs_stat)]

    fdp_quantile = float(kwargs.get("fdp_quantile", 0.90))
    has_labels = kwargs.get("labels", None) is not None
    fdp_col = f"fdp_q{fdp_quantile:g}"

    rows = []
    for target in call_counts:
        target = int(target)
        if finite_obs.size == 0:
            raise ValueError("All observed split statistics are NaN; cannot derive a threshold from call_counts.")
        frac = target / finite_obs.size
        t = float(np.quantile(finite_obs, 1.0 - frac))
        desc = describe_threshold(t, obs_left, obs_right, null_left, null_right, **kwargs)

        row = {
            "target_calls": target,
            "t": desc.t,
            "O": desc.O,
            "E_fp": desc.E_fp,
            "E_fp_over_O": desc.E_fp_over_O,
            "O_over_E_fp": desc.O_over_E_fp,
            "fdp_median": desc.fdp_median,
            fdp_col: desc.fdp_quantile_achieved,
            "fdp_min": desc.fdp_min,
            "fdp_max": desc.fdp_max,
            "mc_pvalue": desc.mc_pvalue,
            "n_ge_observed": desc.n_ge_observed,
        }
        if has_labels:
            row["pi_hat"] = desc.mixture["pi_hat"]
            row["fdp_at_pi_hat"] = desc.mixture["fdp_at_pi_hat"]
            row["fdp_at_pi_low"] = desc.mixture["fdp_at_pi_low"]
            row["fdp_at_pi_high"] = desc.mixture["fdp_at_pi_high"]
        rows.append(row)

    return pd.DataFrame(rows).sort_values("target_calls", ascending=True).reset_index(drop=True)


# ---------------------------------------------------------------------------
# Westfall-Young max-T FWER control
# ---------------------------------------------------------------------------


def maxT_fwer_thresholds(
    null_left: np.ndarray,
    null_right: np.ndarray,
    positions: np.ndarray,
    alpha: float = 0.05,
) -> Dict[str, object]:
    """Westfall-Young max-T family-wise error rate thresholds.

    For each null replicate, take the maximum either-branch-exceeds
    statistic over all node-splits *within a position*; the per-position
    threshold is the ``1 - alpha`` quantile of that per-replicate maximum
    across replicates. Taking the max over (arbitrarily dependent) splits
    within each replicate absorbs the dependence structure exactly — no
    independence assumption is used anywhere here, unlike a naive Bonferroni
    correction across positions.

    A global variant is also returned, taking the max over all splits and
    all positions simultaneously (single family-wise threshold for the
    whole dataset rather than per-position).

    Parameters
    ----------
    null_left, null_right : np.ndarray, shape (R, n_tests)
        Null branch scores.
    positions : np.ndarray, shape (n_tests,)
        The alignment position each test belongs to (used only to group
        columns; not assumed independent across positions).
    alpha : float
        Family-wise error rate to control, per position and globally.

    Returns
    -------
    dict with keys:
        "per_position": {position_value: threshold}
        "global": float
        "alpha": alpha
        "R": number of replicates used
    """
    null_stat = _split_statistic(null_left, null_right)  # (R, n)
    R = null_stat.shape[0]
    positions = np.asarray(positions)
    if positions.shape[0] != null_stat.shape[1]:
        raise ValueError("positions must have one entry per test (column of null_left/null_right).")

    per_position: Dict[object, float] = {}
    for pos in np.unique(positions):
        mask = positions == pos
        sub = null_stat[:, mask]
        if sub.shape[1] == 0:
            per_position[pos] = float("nan")
            continue
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", category=RuntimeWarning)  # all-NaN row -> nan, handled below
            row_max = np.nanmax(sub, axis=1)
        row_max = row_max[np.isfinite(row_max)]
        per_position[pos] = float(np.quantile(row_max, 1 - alpha)) if row_max.size else float("nan")

    with warnings.catch_warnings():
        warnings.simplefilter("ignore", category=RuntimeWarning)
        overall_max = np.nanmax(null_stat, axis=1)
    overall_max = overall_max[np.isfinite(overall_max)]
    global_threshold = float(np.quantile(overall_max, 1 - alpha)) if overall_max.size else float("nan")

    return {"per_position": per_position, "global": global_threshold, "alpha": alpha, "R": R}


# ---------------------------------------------------------------------------
# Matched empirical p-values (secondary/descriptive output)
# ---------------------------------------------------------------------------


def per_test_pvalues(obs: np.ndarray, null: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    """Matched empirical p-value per test, plus Benjamini-Hochberg q-values.

    ``p_i = (1 + #{r : null[r, i] >= obs_i}) / (1 + R)``. The +1 in both
    numerator and denominator (a "add-one" / Clopper-Pearson-style
    correction) guarantees ``p_i >= 1 / (1 + R)`` for every test, so a
    perfectly-extreme observation never reports p=0 — a bare proportion can,
    which silently breaks downstream FDR procedures that divide by p. The
    resolution floor is therefore ``1 / (1 + R)``: with R replicates you
    cannot distinguish significance levels finer than that, no matter how
    extreme the observation.

    q-values are the standard Benjamini-Hochberg step-up adjustment applied
    to the p-values (NaN entries, from NaN test values, are excluded from
    the BH ranking and reported as NaN).

    This is explicitly a SECONDARY, descriptive output. BH assumes either
    independence or positive regression dependence (PRDS) among the test
    statistics; the tests here are known to be massively dependent (nested
    clades, shared AC/posteriors, shared subtrees) in ways that are not
    verified to satisfy PRDS. The primary error-rate guarantee in this
    module is the resampling-based FDP-exceedance control in
    `threshold_at_fdr`, which makes no such assumption. Use these q-values
    for exploratory ranking/reporting only, not as the calling rule.
    """
    obs = np.asarray(obs, dtype=np.float64)
    null = np.asarray(null, dtype=np.float64)
    R = null.shape[0]
    if null.shape[1] != obs.shape[0]:
        raise ValueError("null must have one column per entry of obs.")

    with warnings.catch_warnings():
        warnings.simplefilter("ignore", category=RuntimeWarning)  # NaN comparisons -> False, not an error
        counts = np.sum(null >= obs[np.newaxis, :], axis=0)
    p = (1.0 + counts) / (1.0 + R)
    p = np.where(np.isnan(obs), np.nan, p)
    q = _bh_qvalues(p)
    return p, q


def _bh_qvalues(p: np.ndarray) -> np.ndarray:
    """Standard Benjamini-Hochberg step-up q-values, NaN-safe."""
    p = np.asarray(p, dtype=np.float64)
    q_out = np.full_like(p, np.nan)
    valid_mask = ~np.isnan(p)
    valid_p = p[valid_mask]
    m = valid_p.size
    if m == 0:
        return q_out

    order = np.argsort(valid_p, kind="stable")
    ranked = valid_p[order]
    ranks = np.arange(1, m + 1, dtype=np.float64)
    raw_q = ranked * m / ranks
    # Enforce monotonicity of the step-up adjustment (cumulative min from the largest p-value down).
    q_monotone = np.minimum.accumulate(raw_q[::-1])[::-1]
    q_monotone = np.clip(q_monotone, 0.0, 1.0)

    q_valid = np.empty(m, dtype=np.float64)
    q_valid[order] = q_monotone
    q_out[valid_mask] = q_valid
    return q_out


# ---------------------------------------------------------------------------
# Diagnostic: is a single global threshold justified?
# ---------------------------------------------------------------------------


def exceedance_flatness(
    null: np.ndarray,
    covariates: pd.DataFrame,
    threshold: float,
    n_bins: int = 10,
    max_categorical: int = 20,
) -> pd.DataFrame:
    """Realized null exceedance rate per bin of each covariate, at `threshold`.

    For every test, the realized null exceedance rate is
    ``mean_r(null[r, i] >= threshold)`` (NaN null entries never count as
    exceedances, consistent with the module-wide NaN policy). Binning that
    rate by covariates such as log clade size, log sister clade size,
    distance from root, or alignment position and checking whether the rate
    stays flat is the diagnostic for whether a single GLOBAL threshold is
    justified: if the null exceedance rate is flat across bins, one global
    threshold controls the same false-positive rate everywhere and the old
    per-(event_type, clade-size-decile) binning can be retired; if it is not
    flat, conditioning on that covariate is still needed.

    Parameters
    ----------
    null : np.ndarray, shape (R, n_tests)
        Either the per-branch null array or the split-level statistic
        (e.g. from `_split_statistic`) — whichever unit the caller wants the
        diagnostic computed at.
    covariates : pd.DataFrame, shape (n_tests, ...)
        One row per test, aligned by position with `null`'s columns. Pass
        already-transformed columns (e.g. ``np.log(clade_size_left)``) under
        whatever name you want reported.
    threshold : float
        The candidate global threshold being diagnosed.
    n_bins : int
        Number of quantile bins for numeric covariates with more than
        `max_categorical` distinct values.
    max_categorical : int
        Numeric covariates with at most this many distinct values are
        treated as categorical (one bin per value) rather than quantile-binned.

    Returns
    -------
    Tidy long-format DataFrame with columns
    ``covariate, bin_label, mean_exceedance_rate, n_tests, threshold``,
    one row per (covariate, bin).
    """
    null = np.asarray(null, dtype=np.float64)
    if null.shape[1] != len(covariates):
        raise ValueError("covariates must have one row per column of null.")

    with warnings.catch_warnings():
        warnings.simplefilter("ignore", category=RuntimeWarning)
        exceed_rate = np.mean(null >= threshold, axis=0)

    rows = []
    for col in covariates.columns:
        series = covariates[col]
        if pd.api.types.is_numeric_dtype(series) and series.nunique(dropna=True) > max_categorical:
            bins = pd.qcut(series, q=n_bins, duplicates="drop")
        else:
            bins = series.astype("category")

        tmp = pd.DataFrame({"bin": bins, "rate": exceed_rate})
        grouped = tmp.groupby("bin", observed=True)["rate"].agg(["mean", "count"]).reset_index()
        grouped = grouped.rename(columns={"bin": "bin_label", "mean": "mean_exceedance_rate", "count": "n_tests"})
        grouped["covariate"] = col
        grouped["threshold"] = threshold
        rows.append(grouped[["covariate", "bin_label", "mean_exceedance_rate", "n_tests", "threshold"]])

    if not rows:
        return pd.DataFrame(columns=["covariate", "bin_label", "mean_exceedance_rate", "n_tests", "threshold"])
    return pd.concat(rows, ignore_index=True)


# ---------------------------------------------------------------------------
# Compatibility shim for the existing bin-threshold-dict downstream code
# ---------------------------------------------------------------------------


def as_bin_threshold_dict(
    threshold: float,
    event_types: Iterable[str],
    bin_intervals: Iterable[pd.Interval],
) -> Dict[Tuple[str, pd.Interval], float]:
    """Build a ``{(event_type, bin_interval): threshold}`` dict for a global threshold.

    Matches the shape produced by `calculate_bin_thresholds` and consumed by
    `identify_switches` in
    ``scripts/plot_decoupled_event_switches_clade_adjusted.py`` exactly
    (tuple key of ``(str, pandas.Interval)`` mapped to a float), so the
    existing switch-calling code can be reused unchanged even though our
    threshold is a single global value rather than a per-(event, bin)
    percentile. Because the threshold is global, every key maps to the same
    value — including ``("overall", interval)`` keys, which is what the
    canonical downstream analyses look up when called with
    ``event_specific=False``.
    """
    groups = list(dict.fromkeys(list(event_types) + ["overall"]))  # de-duplicate, preserve order
    intervals = list(bin_intervals)
    value = float(threshold)
    return {(group, interval): value for group in groups for interval in intervals}
