"""Simulation-calibrated null model for BADASP switch calling.

Background
----------
Each (parent node, child branch, alignment position) gets a score

    score(child) = RC(child) - AC * p_AC(child)

The previous switch-calling rule took the 99.9th percentile of the *observed*
scores within each (event_type x clade-size decile) bin. That is circular: it
manufactures exactly 0.1% "positives" per bin by construction and gives no
error-rate guarantee at all.

This module instead calibrates the threshold against a null generated by
simulating sequence evolution on the *same, fixed* tree under the fitted
substitution model, then re-running the identical ASR + scoring pipeline on
each simulated replicate. Because every replicate is scored with the exact
same tree topology and node names, the null reproduces the identical
(node_name, position) test keys as the observed data, and — crucially — it
reproduces the *dependence structure* between tests (nested clades sharing
leaves, sister branches sharing AC and posteriors, adjacent nodes sharing
subtrees). We never assume independence between tests anywhere in this
module; every guarantee below is either a resampling-based statement that is
valid under arbitrary dependence, or is explicitly flagged as a secondary,
descriptive approximation.

Design decisions carried over from the calling code (not re-litigated here):

* The threshold is GLOBAL across event types (Duplication/Speciation/
  Transfer). The simulator never sees event labels, so conditional on tree
  geometry the null score distribution does not depend on the label; making
  the null event-specific would force equal exceedance rates across D/S/T by
  construction and destroy the event-enrichment signal the study wants to
  measure. `event_type` is used only for reporting, never inside the null.
* The reporting unit is the branch (one score per child per node per
  position). The error-control unit is the node-split: a split is
  "discovered" if EITHER of its two branch scores exceeds the threshold.
  The identical either-branch-exceeds rule is applied when counting null
  exceedances, so that observed and null counts are computed by the same
  procedure.

NaN policy (applies uniformly everywhere in this module)
---------------------------------------------------------
Gap positions in a given branch/replicate produce NaN scores. We adopt one
policy and apply it identically to observed and null data:

* A test's exceedance indicator, ``(left >= t) | (right >= t)``, treats NaN
  branch scores as "does not exceed" — this falls out for free in numpy
  because ``NaN >= t`` is always ``False``. A split with one NaN branch and
  one real branch is therefore still tested on its real branch.
* A split with BOTH branches NaN can never exceed any threshold, in either
  observed or null data, and is therefore silently excluded from every count
  (O(t), V_r(t), exceedance rates) without special-casing — it simply never
  contributes.
* Candidate threshold grids and p-value/quantile computations explicitly
  drop NaN entries before sorting so that NaN does not pollute rank
  statistics (numpy sorts NaN as "largest", which would otherwise corrupt
  counts if not accounted for).

A note on `max(left, right)`
-----------------------------
Internally, several routines compute ``np.fmax(left, right)`` as a single
per-split number. This is used *purely as a monotone computational device*
so that a sort + ``searchsorted``/``cumsum`` can answer "how many splits
have either branch >= t" for every t in one pass. It is mathematically
identical to ``(left >= t) | (right >= t)`` for every threshold t (and
``np.fmax`` inherits the NaN policy above: ``fmax(NaN, x) == x``). It is
never used, reported, or interpreted as a biological "combined score" —
the two branches are the real per-test quantities of interest, and nothing
downstream ever looks at left/right through the lens of "which one was
bigger".
"""

from __future__ import annotations

import warnings
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd

# Arrays required in every rep_*.npz null-replicate file. See
# `write_null_replicate` / `load_null_scores` docstrings for the exact format.
_NULL_REPLICATE_SCORE_FIELDS = (
    "score_left",
    "score_right",
    "rc_left",
    "rc_right",
    "ac",
    "p_ac_left",
    "p_ac_right",
)
_NULL_REPLICATE_KEY_FIELDS = ("node_name", "position")
_NULL_REPLICATE_OPTIONAL_KEY_FIELDS = ("left_child", "right_child")


# ---------------------------------------------------------------------------
# Null-replicate file I/O
# ---------------------------------------------------------------------------


def write_null_replicate(
    path: Path,
    node_name: Sequence[str],
    position: Sequence[int],
    score_left: Sequence[float],
    score_right: Sequence[float],
    rc_left: Sequence[float],
    rc_right: Sequence[float],
    ac: Sequence[float],
    p_ac_left: Sequence[float],
    p_ac_right: Sequence[float],
    left_child: Optional[Sequence[str]] = None,
    right_child: Optional[Sequence[str]] = None,
) -> None:
    """Write one simulated-replicate file in the ``rep_*.npz`` format.

    File format (this is the canonical definition consumed by
    `load_null_scores`): a ``.npz`` archive containing, on a single shared
    "test" axis of length ``n_tests`` (one entry per (node_name, position)
    scored in that replicate):

    * ``node_name`` (str array) and ``position`` (int array) — the test key.
      Optionally ``left_child`` / ``right_child`` (str arrays) for
      provenance/debugging.
    * ``score_left``, ``score_right``, ``rc_left``, ``rc_right``, ``ac``,
      ``p_ac_left``, ``p_ac_right`` — all float16 arrays of length
      ``n_tests``, matching the columns of ``raw_node_scores.csv``.

    Every replicate written for a given tree/analysis must share the exact
    same key order (same ``node_name``/``position`` at the same array index)
    as every other replicate and as the observed data, since the whole point
    of simulating on the fixed tree is that null and observed tests line up
    one-to-one. `load_null_scores` validates this and fails loudly if it does
    not hold.
    """
    n = len(node_name)
    arrays: Dict[str, np.ndarray] = {
        "node_name": np.asarray(node_name, dtype=str),
        "position": np.asarray(position, dtype=np.int32),
        "score_left": np.asarray(score_left, dtype=np.float16),
        "score_right": np.asarray(score_right, dtype=np.float16),
        "rc_left": np.asarray(rc_left, dtype=np.float16),
        "rc_right": np.asarray(rc_right, dtype=np.float16),
        "ac": np.asarray(ac, dtype=np.float16),
        "p_ac_left": np.asarray(p_ac_left, dtype=np.float16),
        "p_ac_right": np.asarray(p_ac_right, dtype=np.float16),
    }
    for name, arr in arrays.items():
        if arr.shape[0] != n:
            raise ValueError(f"Array '{name}' has length {arr.shape[0]}, expected {n} (from node_name).")
    if left_child is not None:
        arrays["left_child"] = np.asarray(left_child, dtype=str)
    if right_child is not None:
        arrays["right_child"] = np.asarray(right_child, dtype=str)

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    np.savez(path, **arrays)


def load_null_scores(directory: Path) -> Tuple[np.ndarray, np.ndarray, pd.DataFrame]:
    """Load every ``rep_*.npz`` file in `directory` into stacked null arrays.

    Returns
    -------
    null_left, null_right : np.ndarray, shape (R, n_tests), float32
        Per-replicate branch scores, stacked in file-sort order (R = number
        of replicate files found).
    keys : pd.DataFrame, shape (n_tests, ...)
        The shared test key table (``node_name``, ``position``, and
        ``left_child``/``right_child`` if present), taken from the first
        replicate file.

    All replicates must have identical length and identical key order (see
    `write_null_replicate`); a mismatch raises `ValueError` immediately
    rather than silently truncating or reindexing, since silently
    misaligning null and observed tests would invalidate every downstream
    guarantee in this module.
    """
    directory = Path(directory)
    files = sorted(directory.glob("rep_*.npz"))
    if not files:
        raise FileNotFoundError(f"No 'rep_*.npz' files found in {directory}")

    null_left_chunks: List[np.ndarray] = []
    null_right_chunks: List[np.ndarray] = []
    ref_keys: Optional[pd.DataFrame] = None
    ref_n: Optional[int] = None

    required = set(_NULL_REPLICATE_SCORE_FIELDS) | set(_NULL_REPLICATE_KEY_FIELDS)

    for f in files:
        with np.load(f) as data:
            missing = required - set(data.files)
            if missing:
                raise ValueError(f"Replicate file {f} is missing required arrays: {sorted(missing)}")

            n = data["score_left"].shape[0]
            if ref_n is None:
                ref_n = n
                key_cols = {k: data[k] for k in _NULL_REPLICATE_KEY_FIELDS}
                for k in _NULL_REPLICATE_OPTIONAL_KEY_FIELDS:
                    if k in data.files:
                        key_cols[k] = data[k]
                ref_keys = pd.DataFrame(key_cols)
            elif n != ref_n:
                raise ValueError(
                    f"Replicate {f} has {n} tests but reference replicate {files[0]} has {ref_n}. "
                    "All null replicates must score the identical fixed set of (node, position) tests."
                )
            else:
                if not np.array_equal(data["node_name"], ref_keys["node_name"].to_numpy()) or not np.array_equal(
                    data["position"], ref_keys["position"].to_numpy()
                ):
                    raise ValueError(
                        f"Replicate {f} has a different (node_name, position) key order than reference "
                        f"replicate {files[0]}. Null replicates must be written in a shared, fixed key order."
                    )

            null_left_chunks.append(data["score_left"].astype(np.float32))
            null_right_chunks.append(data["score_right"].astype(np.float32))

    null_left = np.stack(null_left_chunks, axis=0)
    null_right = np.stack(null_right_chunks, axis=0)
    assert ref_keys is not None
    return null_left, null_right, ref_keys


def load_observed_scores(csv_path: Path) -> Tuple[np.ndarray, np.ndarray, pd.DataFrame]:
    """Convenience loader for ``raw_node_scores.csv``.

    Returns ``(obs_left, obs_right, keys)`` where `keys` retains the
    reporting columns (``node_name``, ``event_type``, ``position``,
    ``clade_size_left``, ``clade_size_right``, ``distance_from_root``, ...)
    so callers can join threshold decisions back onto them for reporting.
    """
    df = pd.read_csv(csv_path)
    obs_left = df["badasp_score_left"].to_numpy(dtype=np.float32)
    obs_right = df["badasp_score_right"].to_numpy(dtype=np.float32)
    keys = df.drop(columns=["badasp_score_left", "badasp_score_right"])
    return obs_left, obs_right, keys


# ---------------------------------------------------------------------------
# Core statistic: the either-branch-exceeds rule
# ---------------------------------------------------------------------------


def _split_statistic(left: np.ndarray, right: np.ndarray) -> np.ndarray:
    """Monotone stand-in for the either-branch-exceeds rule.

    ``fmax(left, right) >= t`` is exactly ``(left >= t) | (right >= t)`` for
    every threshold t, including the NaN case (`np.fmax` ignores a single NaN
    operand; a split with both branches NaN yields NaN, and ``NaN >= t`` is
    always False). This lets a single sort answer "how many splits exceed t"
    for every t via `searchsorted`, instead of recomputing the OR at every
    grid point. It is a computational device only, not a reported score.
    """
    return np.fmax(np.asarray(left, dtype=np.float64), np.asarray(right, dtype=np.float64))


# ---------------------------------------------------------------------------
# FDP-exceedance calibrated threshold
# ---------------------------------------------------------------------------


@dataclass
class ThresholdResult:
    """Result of `threshold_at_fdr`.

    ``t`` is None when no candidate threshold in the sweep satisfies the
    criterion (see `threshold_at_fdr` docstring for when this happens).
    ``zero_discoveries`` flags the degenerate-but-valid case where the
    chosen threshold admits O(t) == 0 observed discoveries.
    """

    t: Optional[float]
    O_t: Optional[int]
    E_fp: Optional[float]
    E_fp_over_O: Optional[float]
    fdp_quantile_achieved: Optional[float]
    q: float
    fdp_quantile: float
    R: int
    criterion_met: bool
    zero_discoveries: bool
    sweep: pd.DataFrame
    note: str = ""


def threshold_at_fdr(
    obs_left: np.ndarray,
    obs_right: np.ndarray,
    null_left: np.ndarray,
    null_right: np.ndarray,
    q: float,
    fdp_quantile: float = 0.90,
) -> ThresholdResult:
    """Pick the smallest split-level threshold controlling P(FDP > q).

    For a candidate threshold t:

    * ``O(t)`` = number of observed node-splits with either branch score
      ``>= t`` (NaN-both splits never count, see module docstring).
    * ``V_r(t)`` = the identical either-branch-exceeds count computed on
      null replicate r.
    * ``E[FP](t) = mean_r V_r(t)`` is the point estimate of the expected
      number of false discoveries at t; ``E[FP](t) / O(t)`` estimates the
      false discovery proportion.

    Primary criterion: choose the smallest t (searched over the sorted
    unique *observed* split statistics — O(t) only changes at these
    breakpoints, so it is exactly as informative as a finer grid while being
    only O(n_tests) points) such that the `fdp_quantile` percentile
    (default: 90th) of ``V_r(t) / max(O(t), 1)`` over replicates is ``<= q``.
    This controls ``P(FDP(t) > q) <= 1 - fdp_quantile`` and remains valid
    under arbitrary dependence between tests, because the null replicates
    were generated by simulating on the identical tree and therefore
    reproduce the real dependence structure (shared clades, shared AC/
    posteriors at a node, shared subtrees) rather than assuming independence.

    This is a resampling/Monte-Carlo quantile, not an asymptotic
    approximation: it is only as good as the number of replicates R:
    the achievable resolution/granularity of the estimated tail quantile is
    limited by R, and `E[FP]` and the FDP quantile are themselves noisy
    point estimates from R draws.

    Complexity
    ----------
    Let ``n`` = number of observed node-splits and ``m <= n`` = number of
    grid points (unique finite observed split statistics). Null replicates
    are sorted once with a single vectorized ``np.sort(null_stat, axis=1)``
    call, O(R * n log n). Counting exceedances at every grid point uses
    `searchsorted` against each replicate's sorted (NaN-stripped) row,
    O(R * m log n). Total: O(R * n log n) — no O(m * R * n) double loop.

    Degenerate cases
    ----------------
    * If every observed split statistic is NaN, there is no candidate grid;
      returns a `ThresholdResult` with ``t=None``, ``criterion_met=False``,
      and an explanatory `note`.
    * If no t in the grid satisfies the criterion, returns ``t=None``,
      ``criterion_met=False``, with the full sweep still attached so the
      caller can inspect how close the best candidate came.
    * The chosen t may have ``O(t) == 0`` (no observed discoveries survive)
      — this is a valid, non-error outcome, flagged via
      ``zero_discoveries=True``.
    """
    obs_left = np.asarray(obs_left, dtype=np.float64)
    obs_right = np.asarray(obs_right, dtype=np.float64)
    null_left = np.asarray(null_left, dtype=np.float64)
    null_right = np.asarray(null_right, dtype=np.float64)

    n = obs_left.shape[0]
    if obs_right.shape[0] != n:
        raise ValueError("obs_left and obs_right must have the same length.")
    if null_left.shape != null_right.shape:
        raise ValueError("null_left and null_right must have identical shape.")
    if null_left.shape[1] != n:
        raise ValueError(f"null arrays have {null_left.shape[1]} tests but observed arrays have {n}.")

    R = null_left.shape[0]
    obs_stat = _split_statistic(obs_left, obs_right)
    finite_obs = obs_stat[np.isfinite(obs_stat)]

    empty_sweep = pd.DataFrame(
        columns=["t", "O", "E_fp", "E_fp_over_O", "fdp_quantile_achieved", "meets_criterion"]
    )

    if finite_obs.size == 0:
        return ThresholdResult(
            t=None,
            O_t=None,
            E_fp=None,
            E_fp_over_O=None,
            fdp_quantile_achieved=None,
            q=q,
            fdp_quantile=fdp_quantile,
            R=R,
            criterion_met=False,
            zero_discoveries=False,
            sweep=empty_sweep,
            note="All observed split statistics are NaN; no candidate thresholds exist.",
        )

    t_grid = np.unique(finite_obs)  # ascending
    m = t_grid.shape[0]
    sorted_valid_obs = np.sort(finite_obs)
    idx_obs = np.searchsorted(sorted_valid_obs, t_grid, side="left")
    O_grid = (finite_obs.size - idx_obs).astype(np.int64)  # shape (m,)

    if R == 0:
        return ThresholdResult(
            t=None,
            O_t=None,
            E_fp=None,
            E_fp_over_O=None,
            fdp_quantile_achieved=None,
            q=q,
            fdp_quantile=fdp_quantile,
            R=0,
            criterion_met=False,
            zero_discoveries=False,
            sweep=empty_sweep,
            note="No null replicates (R=0); cannot calibrate a threshold.",
        )

    null_stat = _split_statistic(null_left, null_right)  # (R, n)
    sorted_null = np.sort(null_stat, axis=1)  # NaNs sort to the end of each row; vectorized once, O(R n log n)
    valid_counts = np.sum(~np.isnan(null_stat), axis=1)  # (R,)

    V_grid = np.empty((R, m), dtype=np.int64)
    for r in range(R):
        vc = int(valid_counts[r])
        row_valid = sorted_null[r, :vc]
        idx = np.searchsorted(row_valid, t_grid, side="left")
        V_grid[r] = vc - idx

    E_fp = V_grid.mean(axis=0)
    O_safe = np.maximum(O_grid, 1)
    E_fp_over_O = E_fp / O_safe
    fdp = V_grid / O_safe[np.newaxis, :]
    achieved = np.quantile(fdp, fdp_quantile, axis=0)
    meets = achieved <= q

    sweep = pd.DataFrame(
        {
            "t": t_grid,
            "O": O_grid,
            "E_fp": E_fp,
            "E_fp_over_O": E_fp_over_O,
            "fdp_quantile_achieved": achieved,
            "meets_criterion": meets,
        }
    )

    if not meets.any():
        return ThresholdResult(
            t=None,
            O_t=None,
            E_fp=None,
            E_fp_over_O=None,
            fdp_quantile_achieved=None,
            q=q,
            fdp_quantile=fdp_quantile,
            R=R,
            criterion_met=False,
            zero_discoveries=False,
            sweep=sweep,
            note=f"No threshold in the grid achieves P(FDP > {q}) <= {1 - fdp_quantile:.3g}.",
        )

    chosen_idx = int(np.argmax(meets))  # first True, i.e. smallest t satisfying the criterion
    row = sweep.iloc[chosen_idx]
    return ThresholdResult(
        t=float(row["t"]),
        O_t=int(row["O"]),
        E_fp=float(row["E_fp"]),
        E_fp_over_O=float(row["E_fp_over_O"]),
        fdp_quantile_achieved=float(row["fdp_quantile_achieved"]),
        q=q,
        fdp_quantile=fdp_quantile,
        R=R,
        criterion_met=True,
        zero_discoveries=bool(row["O"] == 0),
        sweep=sweep,
        note="",
    )


# ---------------------------------------------------------------------------
# Westfall-Young max-T FWER control
# ---------------------------------------------------------------------------


def maxT_fwer_thresholds(
    null_left: np.ndarray,
    null_right: np.ndarray,
    positions: np.ndarray,
    alpha: float = 0.05,
) -> Dict[str, object]:
    """Westfall-Young max-T family-wise error rate thresholds.

    For each null replicate, take the maximum either-branch-exceeds
    statistic over all node-splits *within a position*; the per-position
    threshold is the ``1 - alpha`` quantile of that per-replicate maximum
    across replicates. Taking the max over (arbitrarily dependent) splits
    within each replicate absorbs the dependence structure exactly — no
    independence assumption is used anywhere here, unlike a naive Bonferroni
    correction across positions.

    A global variant is also returned, taking the max over all splits and
    all positions simultaneously (single family-wise threshold for the
    whole dataset rather than per-position).

    Parameters
    ----------
    null_left, null_right : np.ndarray, shape (R, n_tests)
        Null branch scores.
    positions : np.ndarray, shape (n_tests,)
        The alignment position each test belongs to (used only to group
        columns; not assumed independent across positions).
    alpha : float
        Family-wise error rate to control, per position and globally.

    Returns
    -------
    dict with keys:
        "per_position": {position_value: threshold}
        "global": float
        "alpha": alpha
        "R": number of replicates used
    """
    null_stat = _split_statistic(null_left, null_right)  # (R, n)
    R = null_stat.shape[0]
    positions = np.asarray(positions)
    if positions.shape[0] != null_stat.shape[1]:
        raise ValueError("positions must have one entry per test (column of null_left/null_right).")

    per_position: Dict[object, float] = {}
    for pos in np.unique(positions):
        mask = positions == pos
        sub = null_stat[:, mask]
        if sub.shape[1] == 0:
            per_position[pos] = float("nan")
            continue
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", category=RuntimeWarning)  # all-NaN row -> nan, handled below
            row_max = np.nanmax(sub, axis=1)
        row_max = row_max[np.isfinite(row_max)]
        per_position[pos] = float(np.quantile(row_max, 1 - alpha)) if row_max.size else float("nan")

    with warnings.catch_warnings():
        warnings.simplefilter("ignore", category=RuntimeWarning)
        overall_max = np.nanmax(null_stat, axis=1)
    overall_max = overall_max[np.isfinite(overall_max)]
    global_threshold = float(np.quantile(overall_max, 1 - alpha)) if overall_max.size else float("nan")

    return {"per_position": per_position, "global": global_threshold, "alpha": alpha, "R": R}


# ---------------------------------------------------------------------------
# Matched empirical p-values (secondary/descriptive output)
# ---------------------------------------------------------------------------


def per_test_pvalues(obs: np.ndarray, null: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    """Matched empirical p-value per test, plus Benjamini-Hochberg q-values.

    ``p_i = (1 + #{r : null[r, i] >= obs_i}) / (1 + R)``. The +1 in both
    numerator and denominator (a "add-one" / Clopper-Pearson-style
    correction) guarantees ``p_i >= 1 / (1 + R)`` for every test, so a
    perfectly-extreme observation never reports p=0 — a bare proportion can,
    which silently breaks downstream FDR procedures that divide by p. The
    resolution floor is therefore ``1 / (1 + R)``: with R replicates you
    cannot distinguish significance levels finer than that, no matter how
    extreme the observation.

    q-values are the standard Benjamini-Hochberg step-up adjustment applied
    to the p-values (NaN entries, from NaN test values, are excluded from
    the BH ranking and reported as NaN).

    This is explicitly a SECONDARY, descriptive output. BH assumes either
    independence or positive regression dependence (PRDS) among the test
    statistics; the tests here are known to be massively dependent (nested
    clades, shared AC/posteriors, shared subtrees) in ways that are not
    verified to satisfy PRDS. The primary error-rate guarantee in this
    module is the resampling-based FDP-exceedance control in
    `threshold_at_fdr`, which makes no such assumption. Use these q-values
    for exploratory ranking/reporting only, not as the calling rule.
    """
    obs = np.asarray(obs, dtype=np.float64)
    null = np.asarray(null, dtype=np.float64)
    R = null.shape[0]
    if null.shape[1] != obs.shape[0]:
        raise ValueError("null must have one column per entry of obs.")

    with warnings.catch_warnings():
        warnings.simplefilter("ignore", category=RuntimeWarning)  # NaN comparisons -> False, not an error
        counts = np.sum(null >= obs[np.newaxis, :], axis=0)
    p = (1.0 + counts) / (1.0 + R)
    p = np.where(np.isnan(obs), np.nan, p)
    q = _bh_qvalues(p)
    return p, q


def _bh_qvalues(p: np.ndarray) -> np.ndarray:
    """Standard Benjamini-Hochberg step-up q-values, NaN-safe."""
    p = np.asarray(p, dtype=np.float64)
    q_out = np.full_like(p, np.nan)
    valid_mask = ~np.isnan(p)
    valid_p = p[valid_mask]
    m = valid_p.size
    if m == 0:
        return q_out

    order = np.argsort(valid_p, kind="stable")
    ranked = valid_p[order]
    ranks = np.arange(1, m + 1, dtype=np.float64)
    raw_q = ranked * m / ranks
    # Enforce monotonicity of the step-up adjustment (cumulative min from the largest p-value down).
    q_monotone = np.minimum.accumulate(raw_q[::-1])[::-1]
    q_monotone = np.clip(q_monotone, 0.0, 1.0)

    q_valid = np.empty(m, dtype=np.float64)
    q_valid[order] = q_monotone
    q_out[valid_mask] = q_valid
    return q_out


# ---------------------------------------------------------------------------
# Diagnostic: is a single global threshold justified?
# ---------------------------------------------------------------------------


def exceedance_flatness(
    null: np.ndarray,
    covariates: pd.DataFrame,
    threshold: float,
    n_bins: int = 10,
    max_categorical: int = 20,
) -> pd.DataFrame:
    """Realized null exceedance rate per bin of each covariate, at `threshold`.

    For every test, the realized null exceedance rate is
    ``mean_r(null[r, i] >= threshold)`` (NaN null entries never count as
    exceedances, consistent with the module-wide NaN policy). Binning that
    rate by covariates such as log clade size, log sister clade size,
    distance from root, or alignment position and checking whether the rate
    stays flat is the diagnostic for whether a single GLOBAL threshold is
    justified: if the null exceedance rate is flat across bins, one global
    threshold controls the same false-positive rate everywhere and the old
    per-(event_type, clade-size-decile) binning can be retired; if it is not
    flat, conditioning on that covariate is still needed.

    Parameters
    ----------
    null : np.ndarray, shape (R, n_tests)
        Either the per-branch null array or the split-level statistic
        (e.g. from `_split_statistic`) — whichever unit the caller wants the
        diagnostic computed at.
    covariates : pd.DataFrame, shape (n_tests, ...)
        One row per test, aligned by position with `null`'s columns. Pass
        already-transformed columns (e.g. ``np.log(clade_size_left)``) under
        whatever name you want reported.
    threshold : float
        The candidate global threshold being diagnosed.
    n_bins : int
        Number of quantile bins for numeric covariates with more than
        `max_categorical` distinct values.
    max_categorical : int
        Numeric covariates with at most this many distinct values are
        treated as categorical (one bin per value) rather than quantile-binned.

    Returns
    -------
    Tidy long-format DataFrame with columns
    ``covariate, bin_label, mean_exceedance_rate, n_tests, threshold``,
    one row per (covariate, bin).
    """
    null = np.asarray(null, dtype=np.float64)
    if null.shape[1] != len(covariates):
        raise ValueError("covariates must have one row per column of null.")

    with warnings.catch_warnings():
        warnings.simplefilter("ignore", category=RuntimeWarning)
        exceed_rate = np.mean(null >= threshold, axis=0)

    rows = []
    for col in covariates.columns:
        series = covariates[col]
        if pd.api.types.is_numeric_dtype(series) and series.nunique(dropna=True) > max_categorical:
            bins = pd.qcut(series, q=n_bins, duplicates="drop")
        else:
            bins = series.astype("category")

        tmp = pd.DataFrame({"bin": bins, "rate": exceed_rate})
        grouped = tmp.groupby("bin", observed=True)["rate"].agg(["mean", "count"]).reset_index()
        grouped = grouped.rename(columns={"bin": "bin_label", "mean": "mean_exceedance_rate", "count": "n_tests"})
        grouped["covariate"] = col
        grouped["threshold"] = threshold
        rows.append(grouped[["covariate", "bin_label", "mean_exceedance_rate", "n_tests", "threshold"]])

    if not rows:
        return pd.DataFrame(columns=["covariate", "bin_label", "mean_exceedance_rate", "n_tests", "threshold"])
    return pd.concat(rows, ignore_index=True)


# ---------------------------------------------------------------------------
# Compatibility shim for the existing bin-threshold-dict downstream code
# ---------------------------------------------------------------------------


def as_bin_threshold_dict(
    threshold: float,
    event_types: Iterable[str],
    bin_intervals: Iterable[pd.Interval],
) -> Dict[Tuple[str, pd.Interval], float]:
    """Build a ``{(event_type, bin_interval): threshold}`` dict for a global threshold.

    Matches the shape produced by `calculate_bin_thresholds` and consumed by
    `identify_switches` in
    ``scripts/plot_decoupled_event_switches_clade_adjusted.py`` exactly
    (tuple key of ``(str, pandas.Interval)`` mapped to a float), so the
    existing switch-calling code can be reused unchanged even though our
    threshold is a single global value rather than a per-(event, bin)
    percentile. Because the threshold is global, every key maps to the same
    value — including ``("overall", interval)`` keys, which is what the
    canonical downstream analyses look up when called with
    ``event_specific=False``.
    """
    groups = list(dict.fromkeys(list(event_types) + ["overall"]))  # de-duplicate, preserve order
    intervals = list(bin_intervals)
    value = float(threshold)
    return {(group, interval): value for group in groups for interval in intervals}
